# Generated by Django 4.0.6 on 2022-07-20 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('president', models.CharField(max_length=50)),
                ('vice_president', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=250)),
                ('numero_impot', models.CharField(max_length=50)),
                ('date_creation', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipeSecours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('nombre_member', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('post_nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=250)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=10)),
                ('adresse', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=50)),
                ('etat_civil', models.CharField(choices=[('Celibataire', 'Celibataire'), ('Marié', 'Marié'), ('Veuf', 'Veuf')], max_length=50)),
                ('numero_national', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_rest.utilisateur')),
            ],
            bases=('api_rest.utilisateur',),
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=250)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.association')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('alerte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_rest.alerte')),
                ('equipe_secours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_rest.equipesecours')),
            ],
        ),
        migrations.AddField(
            model_name='alerte',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_rest.utilisateur'),
        ),
        migrations.CreateModel(
            name='Motard',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_rest.utilisateur')),
                ('matricule', models.CharField(max_length=50)),
                ('parking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_rest.parking')),
            ],
            bases=('api_rest.utilisateur',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Personne', 'Personne'), ('Colit', 'Colit')], max_length=20)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Effectué', 'Effectué'), ('En entente', 'En entente')], max_length=20)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_rest.client')),
                ('motard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_rest.motard')),
            ],
        ),
    ]
