# Generated by Django 4.1 on 2022-10-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_alter_utilisateur_numero_national'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='profils/'),
        ),
    ]
