# Generated by Django 4.1.2 on 2022-10-19 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_alter_utilisateur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='statut',
            field=models.CharField(choices=[('En demande', 'En demande'), ('En cours', 'En cours'), ('Finis', 'Finis')], max_length=20),
        ),
    ]
